<?php
require_once __DIR__ . "/../../config/database.php";
/** @var mysqli $conn */
require_once __DIR__ . "/../auth.php";
requireLogin();
require_once __DIR__ . "/_helpers.php";
orderRequireAccess();
$id=(int)($_GET['id']??0); if($id<=0){header("Location: /huongviet/admin/orders/index.php");exit;}
$order=getOrder($conn,$id); if(!$order){header("Location: /huongviet/admin/orders/index.php");exit;}
if($order['payment_status']==='Đã thanh toán'){header("Location: /huongviet/admin/orders/index.php?error=".urlencode("Order này đã được thanh toán."));exit;}
if($order['order_status']==='Đã hủy'){header("Location: /huongviet/admin/orders/index.php?error=".urlencode("Không thể thanh toán order đã hủy."));exit;}
if($order['order_status']==='Đã hoàn thành'){header("Location: /huongviet/admin/orders/index.php?error=".urlencode("Order này đã hoàn thành."));exit;}
if($order['payment_status']!=='Chưa thanh toán'||$order['order_status']!=='Đang phục vụ'){header("Location: /huongviet/admin/orders/index.php?error=".urlencode("Thao tác không hợp lệ với trạng thái hiện tại."));exit;}
$errors=[];$methods=['Tiền mặt','Chuyển khoản','Thẻ ngân hàng'];$discount=(float)$order['discount'];$method=$order['payment_method']?:'Tiền mặt';$note='';
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){ $freshOrder=getOrder($conn,$id); if(!$freshOrder||$freshOrder['payment_status']!=='Chưa thanh toán'||$freshOrder['order_status']!=='Đang phục vụ'){header("Location: /huongviet/admin/orders/index.php?error=".urlencode("Thao tác không hợp lệ với trạng thái hiện tại."));exit;} $discount=(float)($_POST['discount']??0); $method=$_POST['payment_method']??'Tiền mặt'; $note=trim($_POST['payment_note']??''); if($discount<0||$discount>(float)$freshOrder['total_amount'])$errors[]='Giảm giá không hợp lệ.'; if(!in_array($method,$methods,true))$method='Tiền mặt'; if(!$errors){mysqli_begin_transaction($conn);try{$final=(float)$freshOrder['total_amount']-$discount;$ps='Đã thanh toán';$os='Đã hoàn thành';$stmt=mysqli_prepare($conn,"UPDATE orders SET discount=?, final_amount=?, payment_method=?, payment_status=?, order_status=? WHERE id=?");mysqli_stmt_bind_param($stmt,"ddsssi",$discount,$final,$method,$ps,$os,$id);mysqli_stmt_execute($stmt);$stmt=mysqli_prepare($conn,"INSERT INTO payments(order_id,payment_method,amount,note,payment_date) VALUES(?,?,?,?,NOW())");mysqli_stmt_bind_param($stmt,"isds",$id,$method,$final,$note);mysqli_stmt_execute($stmt);if($freshOrder['table_id']){$s='Trống';$tid=(int)$freshOrder['table_id'];$stmt=mysqli_prepare($conn,"UPDATE tables_restaurant SET status=? WHERE id=?");mysqli_stmt_bind_param($stmt,"si",$s,$tid);mysqli_stmt_execute($stmt);}mysqli_commit($conn);header("Location: /huongviet/admin/orders/view.php?id=".$id);exit;}catch(Throwable $e){mysqli_rollback($conn);$errors[]='Không thể thanh toán: '.$e->getMessage();}}}
orderHeader("Thanh toán hóa đơn");
?>
<main class="container py-4"><div class="card border-0 shadow-sm"><div class="card-body p-4"><div class="d-flex justify-content-between mb-3"><h1 class="h3 mb-0">Thanh toán hóa đơn #<?php echo $id;?></h1><a class="btn btn-outline-secondary" href="/huongviet/admin/orders/view.php?id=<?php echo $id;?>">Quay lại</a></div><?php if($errors){?><div class="alert alert-danger"><?php foreach($errors as $er)echo'<div>'.e($er).'</div>';?></div><?php }?><form method="POST" class="row g-3"><div class="col-md-4"><label class="form-label">Tổng tiền</label><input class="form-control" value="<?php echo orderMoney($order['total_amount']);?>" disabled></div><div class="col-md-4"><label class="form-label">Giảm giá</label><input type="number" min="0" max="<?php echo (float)$order['total_amount'];?>" class="form-control" name="discount" value="<?php echo e($discount);?>"></div><div class="col-md-4"><label class="form-label">Phương thức</label><select class="form-select" name="payment_method"><?php foreach($methods as $m){?><option value="<?php echo e($m);?>" <?php echo $method===$m?'selected':'';?>><?php echo e($m);?></option><?php }?></select></div><div class="col-12"><label class="form-label">Ghi chú thanh toán</label><textarea class="form-control" name="payment_note"><?php echo e($note);?></textarea></div><div class="col-12"><button class="btn btn-success">Xác nhận thanh toán</button></div></form></div></div></main><?php orderFooter(); ?>
